### ISSUE TITLE
How to call Activity from one of the view.

### ISSUE THREAD

**Issue by naveenkumarmallappa** [waleedsarwar86/BottomNavigationDemo#3]
When select one particular item in Bottom Bar I want to start new activity.

**Comment by phanthinh** [comment]
why closed this issue? I have similar issue

**Comment by waleedsarwar86** [comment]
@phanthinh  if you want to start a new activity when one particular tab in bottom bar is clicked.Just create a layout which look like a bottom bar and listen for click event on that tabs.Then you will be able to start a new activity or replace fragment its up to you.

**Comment by phanthinh** [comment]
I have tried to custom this code but still hard to work.
